server:
  port: 8000
  servlet:
    context-path: /api
logging.level.root: INFO

info:
  app:
    name: Label Printing service
    description: Label Printing service

spring:
  application:
    name: label-printing-service
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

swagger.enabled: true

management:
 endpoints:
  enabled-by-default: false
  web:
   exposure.include: health
 endpoint:
  info:
   enabled: true
  health:
   enabled: true
   show-details: always
  loggers:
   enabled: true
app:
  folders:
    path:
      data: data/in
      success: data/success
      failure: data/failure
  remote:
    apis:
      success: http://localhost:1234
      failure: http://localhost:4567